[window]
opacity = 0.99
decorations = "Full" 
option_as_alt = "Both"

[font]
size = 13

[font.bold]
family = "GoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "GoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "GoMono Nerd Font"
style = "Italic"

[font.normal]
family = "GoMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[mouse.bindings]]
action = "Paste"
mouse = "Right"
mods = "Control"

[selection]
save_to_clipboard = true
